/*
    Eslint config file generated by ChatGPT based on provided `SICP, JavaScript Adaptation, Source Style Guide, PKD Version 2024/25`
 */
import {defineConfig} from "eslint/config";
import tsParser from "@typescript-eslint/parser";
import tsPlugin from "@typescript-eslint/eslint-plugin";

export default defineConfig([
    {
        files: ["**/*.ts"],
        languageOptions: {
            parser: tsParser,
            ecmaVersion: 2022,
            sourceType: "module"
        },
        plugins: {
            "@typescript-eslint": tsPlugin
        },
        rules: {
            /* ======================================================
               LINE LENGTH & WHITESPACE
            ====================================================== */

            "max-len": ["error", {code: 80, tabWidth: 4}],
            "no-trailing-spaces": "error",
            "eol-last": ["error", "always"],
            "indent": ["error", 4],
            "no-mixed-spaces-and-tabs": "error",

            /* ======================================================
               SPACING
            ====================================================== */

            "space-in-parens": ["error", "never"],
            "comma-spacing": ["error", {before: false, after: true}],
            "space-infix-ops": "error",
            "keyword-spacing": ["error", {before: true, after: true}],
            "space-before-blocks": ["error", "always"],
            "space-before-function-paren": [
                "error",
                {
                    anonymous: "never",
                    named: "never",
                    asyncArrow: "always"
                }
            ],

            /* ======================================================
               BRACES & BLOCKS
            ====================================================== */

            "brace-style": ["error", "1tbs", {allowSingleLine: false}],
            "curly": ["error", "all"],
            "nonblock-statement-body-position": ["error", "below"],
            "no-else-return": "off",

            /* ======================================================
               VARIABLES & SHADOWING
            ====================================================== */

            "no-shadow": "off",
            "@typescript-eslint/no-shadow": "error",

            "no-unused-vars": "off",
            "@typescript-eslint/no-unused-vars": [
                "error",
                {argsIgnorePattern: "^_"}
            ],

            /* ======================================================
               NAMING CONVENTION (snake_case)
            ====================================================== */

            "@typescript-eslint/naming-convention": [
                "error",

                {
                    selector: "default",
                    format: ["snake_case"]
                },

                {
                    selector: "variable",
                    format: ["snake_case", "UPPER_CASE"]
                },

                {
                    selector: "function",
                    format: ["snake_case"]
                },

                {
                    selector: "parameter",
                    format: ["snake_case"]
                },

                {
                    selector: "typeParameter",
                    format: ["PascalCase"]
                }
            ],

            /* ======================================================
               TYPESCRIPT RULES (PKD)
            ====================================================== */

            "@typescript-eslint/no-explicit-any": "error",

            "@typescript-eslint/explicit-function-return-type": [
                "error",
                {allowExpressions: false}
            ],

            "@typescript-eslint/array-type": [
                "error",
                {default: "generic"}
            ],

            /* ======================================================
               CONDITIONAL STYLE
            ====================================================== */

            "operator-linebreak": [
                "error",
                "before",
                {
                    overrides: {
                        "?": "before",
                        ":": "before"
                    }
                }
            ],

            "arrow-body-style": ["error", "as-needed"],

            /* ======================================================
               IMPORTS
            ====================================================== */

            "no-duplicate-imports": "error",

            /* ======================================================
               GENERAL SAFETY
            ====================================================== */

            "no-var": "error",
            "prefer-const": "error",
            "no-redeclare": "error",
            "no-unreachable": "error"
        }
    }
]);